# Default values for geonetwork ncea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#target k8s namespace
# namespace: geonetwork
georeplicaCount: 1

geoimage:  
  repository: $(containerRepostitoryFullPath)
  tag: pipeline
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: &gn_host "geonetwork"
fullnameOverride: "geonetwork" 

geoservice:
  type: ClusterIP
  port: 8080

#resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

georesources:
  resources:
    requests:
      memory: "1200Mi"
      cpu: "250m"
    limits:
      memory: "1500Mi"
      cpu: "1400m"

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  name: geonetwork-ingress
  enabled: true
  classname: nginx
  host: $(ingressHostname)
  path: /
  pathType: Prefix

#database type
db_type: postgres

postgres:
  host: $(postgresHostname)
  port: "5432"
  dbuser: $(postgresDbUser)
  password: $(postgresDbPassword)
  dbname: $(postgresDbName)

kibana:
  host: $(kibanaHostName)
  port: 5601
  name: $(kibanaInstanceName)

# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

elasticsearch:
  name: elasticsearch-master
  host: elasticsearch-master
  port: 9200
  protocol: https
  # values override for subchart elasticsearch
  
pvc:
  geoCataloguePvcName: geonetwork-azuredisk-pvc
  # initial size for geonetwork catalogue data
  geoCataloguePvcSize: 4Gi  
  geoCatalogueStorageClassName: dynamic-premium-zrs # Class for managed Azure disks
  geoMetaDataFileShareName: ncea-enricher-fileshare-pvc #This will reference the existing fileshare PVC created by enricher in 'nceafrontend' namespace
  geoMetaDataFileShareSize: 10Gi

peSaFileshare:
  storageAccountResourceGroup: $(storageAccountResourceGroup)
  storageAccountName: $(storageAccountName)
  storageAccountFilePrivateEndpointFqdn: $(storageAccountFilePrivateEndpointFqdn)
  geoStorageAccountShareName: metadata-import

  
