apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: "disk.csi.azure.com"
  name: {{ .Values.pv.elasticIndexPvName }}
spec:
  capacity:
    storage: {{ .Values.pv.elasticIndexPvSize }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.elasticIndexStorageClassName }}
  csi:
    driver: disk.csi.azure.com
    volumeHandle: {{ .Values.pv.elasticIndexPvDiskResourceId }}
    volumeAttributes:
      fsType: ext4