{{- if .Values.create_kibana_pod }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.kibana.name }}
  annotations:
    geonetwork.version: {{ .Chart.Version }}
  labels:
      geonetwork-ncea/app: {{ $.Values.kibana.name }}
      geonetwork-ncea/siteName: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      geonetwork-ncea/app: {{ $.Values.kibana.name }}
      geonetwork-ncea/siteName: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        geonetwork-ncea/app: {{ $.Values.kibana.name }}
        geonetwork-ncea/siteName: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ $.Values.kibana.name }}
          image: "{{ .Values.kibana.repository }}:{{ .Values.kibana.tag }}"
          imagePullPolicy: {{ .Values.kibana.pullPolicy }}
          env:
            #- name: ELASTICSEARCH_URL
            #  value: {{ .Values.elasticsearch.url }} 
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.elasticsearch.host }} 
            - name: ELASTICSEARCH_PORT
              value: "{{ .Values.elasticsearch.port }}"            
            - name: KIBANA_INDEX
              value: .dashboards
            - name: SERVER_BASEPATH
              value: /geonetwork/dashboards
            - name: SERVER_NAME
              value: {{ $.Values.kibana.name }}
            - name: SERVER_REWRITEBASEPATH
              value: "false"
            - name: XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
              value: "true"
          ports:
            - name: tcp
              containerPort: 5601
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end}}