{{- if .Values.create_kibana_pod }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.kibana.name }}
  annotations:
    geonetwork.version: {{ .Chart.Version }}
  labels:
      geonetwork-ncea/app: {{ $.Values.kibana.name }}
      geonetwork-ncea/siteName: {{ .Release.Name }}
spec:
  type: {{ .Values.kibana.serviceType }}
  ports:
    - port: {{ .Values.kibana.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
      geonetwork-ncea/app: {{ $.Values.kibana.name }}
      geonetwork-ncea/siteName: {{ .Release.Name }}
{{- end}}