
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - feature/*

stages:
- stage: 'Build'
  displayName: 'Build GeoNetwork App'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: DEFRA-COMMON-ubuntu2204-SSV3
    variables:
      - template: pipeline/geoupgrade/variables-build.yml      
    steps:
      - template: pipeline/geoupgrade/steps-build-and-test.yaml
      - template: pipeline/geoupgrade/steps-build-and-push-docker-images.yaml
